before:
  hooks:
    - go mod download
    - go mod tidy
builds:
- env:
  - CGO_ENABLED=0
  ldflags:
    - -s -w -X github.com/k1LoW/evry.version={{.Version}} -X github.com/k1LoW/evry.commit={{.FullCommit}} -X github.com/k1LoW/evry.date={{.Date}} -X github.com/k1LoW/evry/version.Version={{.Version}}
archives:
-
  id: evry-archive
  name_template: '{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
  format_overrides:
    - goos: darwin
      format: zip
  files:
    - CREDITS
    - README.md
    - CHANGELOG.md
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Version }}-next"
changelog:
  skip: true
brews:
-
  name: evry
  github:
    owner: k1LoW
    name: homebrew-tap
  commit_author:
    name: k1LoW
    email: k1lowxb@gmail.com
  homepage: https://github.com/k1LoW/evry
  description: '`evry` split STDIN stream and execute specified command **every** N lines/seconds.'
  install: bin.install 'evry'
