before:
  hooks:
    - go mod download
    - go mod tidy
builds:
-
  id: evry-linux
  env:
    - CGO_ENABLED=0
  goos:
    - linux
  ldflags:
    - -s -w -X github.com/k1LoW/evry.version={{.Version}} -X github.com/k1LoW/evry.commit={{.FullCommit}} -X github.com/k1LoW/evry.date={{.Date}} -X github.com/k1LoW/evry/version.Version={{.Version}}
-
  id: evry-darwin
  env:
    - CGO_ENABLED=0
  goos:
    - darwin
  ldflags:
    - -s -w -X github.com/k1LoW/evry.version={{.Version}} -X github.com/k1LoW/evry.commit={{.FullCommit}} -X github.com/k1LoW/evry.date={{.Date}} -X github.com/k1LoW/evry/version.Version={{.Version}}
archives:
-
  id: evry-archive
  name_template: '{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
  format_overrides:
    - goos: darwin
      format: zip
  files:
    - CREDITS
    - README.md
    - CHANGELOG.md
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Version }}-next"
changelog:
  skip: true
dockers:
  -
    goos: linux
    goarch: amd64
    image_templates:
      - 'ghcr.io/k1low/evry:v{{ .Version }}'
      - 'ghcr.io/k1low/evry:latest'
    dockerfile: Dockerfile
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source=https://github.com/k1LoW/evry"
    extra_files:
      - scripts/entrypoint.sh
brews:
  -
    name: evry
    ids:
      - evry-archive
    tap:
      owner: k1LoW
      name: homebrew-tap
    commit_author:
      name: k1LoW
      email: k1lowxb@gmail.com
    homepage: https://github.com/k1LoW/evry
    description: evry split STDIN stream and execute specified command every N lines/seconds.
    license: MIT
nfpms:
  - id: evry-nfpms
    file_name_template: "{{ .ProjectName }}_{{ .Version }}-1_{{ .Arch }}"
    builds:
      - evry-linux
    homepage: https://github.com/k1LoW/evry
    maintainer: Ken'ichiro Oyama <k1lowxb@gmail.com>
    description: evry split STDIN stream and execute specified command every N lines/seconds
    license: MIT
    formats:
      - apk
      - deb
      - rpm
    bindir: /usr/bin
    epoch: 1
