language: go
go:
  - 1.12.x
  - master
matrix:
  allow_failures:
    - go: master
addons:
  apt:
    update: true
before_install:
  - sudo pip install codecov
  - make depsdev
script:
  - make ci
after_script:
  - codecov
